### ISSUE TITLE
Parameter orderNumber doesn't seem to exist 

### ISSUE THREAD

**Issue by ordago** [creagia/redsys-php#28]
I tried the code from the readme

```php
$redsysRequest = RedsysRequest::create(
    $redsysClient,
    new RequestParameters(
        amountInCents: 123_45,
        orderNumber: '22013100005',
        currency: Currency::EUR,
        transactionType: TransactionType::Autorizacion,
        merchantUrl: 'https://example.com/redsysNotification',
        urlOk: 'https://example.com/paymentOk',
        urlKo: 'https://example.com/paymentKo',
    )
);
```

Creagia\Redsys\Support\Signature::calculateSignature(): Argument #2 ($order) must be of type string, null given, called in [...]]\vendor\creagia\redsys-php\src\RedsysRequest.php on line 68

https://github.com/creagia/redsys-php/blob/9135739b1e4956991e9d407866de4866388bc29d/src/Support/RequestParameters.php#L35-L37

It seems to be just `order`.

**Comment by ordago** [comment]
Created PR #29

**Comment by dtorras** [comment]
Thanks for the PR!
